version: '2'
services:
  api:
    container_name: cufeedback_api
    image: cufeedback/cmd/api
    build:
      context: .
      dockerfile: go/Dockerfile
      args:
        package: api
    command: ["/go/bin/api"]
    environment:
      - DB_URL=postgres://cufeed@postgres/cufeed?sslmode=disable
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=cufeed
      - DATABASE_USER=cufeed
      - DATABASE_PASS=cufeed
      - PORT=8002
    links:
      - postgres:postgres
    ports:
      - "8002:8002"

  postgres:
    container_name: cufeedback_postgres
    image: cufeedback/postgres
    build: postgres
    environment:
      - DB_USER=cufeed
      - DB_NAME=cufeed
    ports:
      - '5432:5432'     