version: '2'
services:
  api:
    container_name: cufixit_api
    image: cufixit/cmd/api
    build:
      context: ./go
      dockerfile: Dockerfile
      args:
        package: api
    command: ["./wait-for-postgres.sh", "/go/bin/api"]
    environment:
      - DB_URL=postgres://cufix@postgres/cufix?sslmode=disable
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=cufix
      - DATABASE_USER=cufix
      - DATABASE_PASS=cufix
      - PORT=8002
    links:
      - postgres:postgres
    ports:
      - "8002:8002"

  postgres:
    container_name: cufixit_postgres
    image: cufixit/postgres
    build: postgres
    environment:
      - DB_USER=cufix
      - DB_NAME=cufix
    ports:
      - '5432:5432'     